---
title: "Using fluEvidenceSynthesis to predict efficacy of different vaccination scenarios"
author: "Edwin van Leeuwen"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vaccination scenario}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction

This package implements all the tools needed to analyse and compare the effectiveness of different Influenza vaccine programs (see Baguelin et al. (2013) for more details). This analysis has two main steps.

#. Parameter inference using existing model
#. Simulation of different possible vaccination strategies using the inferred parameters

This vignette will focus on how the fluEvidenceSythesis package can be used to perform the second step. For details on the first step see the inference vignette.

To test the efficacy of different vaccination scenarios you first need to create a custom vaccination scenario. A vaccination scenario specifies the rate of vaccination per day of each age group and risk group during a given period. The epidemiological model is then run with this scenario. To run the model we need to specify the epidemiological parameters that we inferred by fitting the model to our Influenza data (see inference vignette).

# Example

```{r, eval=FALSE}
library("fluEvidenceSynthesis")

# Create vaccination scenario
vaccine_calendar <- list(
  "efficacy" = c(0.7,0.7,0.7,0.7,0.7,0.7,0.3),
  "calendar" = matrix(rep(0,21*3),ncol=21),
  "dates" =  c(as.Date("2010-10-01"), as.Date("2010-11-01"),
               as.Date("2010-12-01"), as.Date("2010-01-01"))
)

# Set rate of vaccine uptake for different dates/age groups
vaccine_calendar$calendar[1,c(7,14,21)] <- 0.02
vaccine_calendar$calendar[2,c(7,14,21)] <- 0.005
vaccine_calendar$calendar[3,c(7,14,21)] <- 0.005

# Set daily uptake for first month, for high risk young children
vaccine_calendar$calendar[1,c(8,9)] <- 0.02

# Load needed data
data("age_sizes")
data("polymod_uk")
data("inference.results")

# This returns the total size of the outbreak given the vaccination scenario and the
# 1000th posterior (mcmc) sample
vaccinationScenario( age_sizes=age_sizes[,1], vaccine_calendar=vaccine_calendar,
                     polymod_data=as.matrix(polymod_uk),
                     contact_ids=inference.results$contact.ids[1000,],
                     parameters=inference.results$batch[1000,]
                    )
```

The above shows how to use a specific posterior (mcmc) sample to create one prediction. In general you should have a number of samples from the posterior and you call vaccinationScenario using each of those samples. This will result in a posterior distribution for the predicted efficacy of your vaccinationScenario. This can then be used for further analysis, such as the cost effectiveness of your analysis.

The `vaccine_calendar` object defines the needed parameters for a certain vaccine scenario. With efficacy a vector defining the efficacy of the vaccine for each of the 7 age groups. The calendar a matrix holding daily uptakes rates. The first 7 columns are low risk age groups, second the high risk groups. Finally the dates give the starting dates for each of the rows of the calendar matrix. The last date in the date vector is the last date of vaccination. After that date all uptake rates are set back to zero.

# References

Baguelin, Marc, Stefan Flasche, Anton Camacho, Nikolaos Demiris, Elizabeth Miller, and W. John Edmunds. ‘Assessing Optimal Target Populations for Influenza Vaccination Programmes: An Evidence Synthesis and Modelling Study.’ PLoS Med 10, no. 10 (2013): e1001527. doi:10.1371/journal.pmed.1001527.

