// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// cholesky
Eigen::MatrixXd cholesky(SEXP A);
RcppExport SEXP fluEvidenceSynthesis_cholesky(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type A(ASEXP);
    __result = Rcpp::wrap(cholesky(A));
    return __result;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP fluEvidenceSynthesis_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello_world());
    return __result;
END_RCPP
}
// getIMMDate
Rcpp::Date getIMMDate(int mon, int year);
RcppExport SEXP fluEvidenceSynthesis_getIMMDate(SEXP monSEXP, SEXP yearSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type mon(monSEXP);
    Rcpp::traits::input_parameter< int >::type year(yearSEXP);
    __result = Rcpp::wrap(getIMMDate(mon, year));
    return __result;
END_RCPP
}
// useCpp11
int useCpp11();
RcppExport SEXP fluEvidenceSynthesis_useCpp11() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(useCpp11());
    return __result;
END_RCPP
}
// vaccination_scenario
bool vaccination_scenario(std::vector<size_t> age_sizes, SEXP vaccine_calendar);
RcppExport SEXP fluEvidenceSynthesis_vaccination_scenario(SEXP age_sizesSEXP, SEXP vaccine_calendarSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<size_t> >::type age_sizes(age_sizesSEXP);
    Rcpp::traits::input_parameter< SEXP >::type vaccine_calendar(vaccine_calendarSEXP);
    __result = Rcpp::wrap(vaccination_scenario(age_sizes, vaccine_calendar));
    return __result;
END_RCPP
}
