# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' MCMC based inference of the parameter values given the different data sets
#'
#' @param age_sizes A vector with the population size by each age {1,2,..}
#' @param ili The number of Influenza-like illness cases per week
#' @param mon_pop The number of people monitored for ili
#' @param n_pos The number of positive samples for the given strain (per week)
#' @param n_samples The total number of samples tested 
#' @param vaccine_calendar A vaccine calendar valid for that year
#' @param polymod_data Contact data for different age groups
#' @param init_sample The initial parameters needed to run the ODE model (typically one of the posterior sample created when running the inference)
#' @param mcmc_chain_length The number of MCMC steps to sample from
#' @param thinning Keep every so many samples
#' @param burn_in The number of initial samples to skip
#' @return A vector with posterior samples of the parameters (length of \code{mcmc_chain_length}/\code{thinning})
#'
#'
inference <- function(age_sizes, ili, mon_pop, n_pos, n_samples, vaccine_calendar, polymod_data, init_sample, mcmc_chain_length = 100000L, burn_in = 10000L, thinning = 100L) {
    .Call('fluEvidenceSynthesis_inference', PACKAGE = 'fluEvidenceSynthesis', age_sizes, ili, mon_pop, n_pos, n_samples, vaccine_calendar, polymod_data, init_sample, mcmc_chain_length, burn_in, thinning)
}

#' Update means when a new posterior sample is calculated
#'
#' @param means the current means of the parameters
#' @param v the new parameter values
#' @param n The number of posterior (mcmc) samples taken till now
#' @return The updated means given the new parameter sample
#'
.updateMeans <- function(means, v, n) {
    .Call('fluEvidenceSynthesis_updateMeans', PACKAGE = 'fluEvidenceSynthesis', means, v, n)
}

#' Update covariance matrix of posterior parameters
#'
#' Used to enable faster mixing of the mcmc chain
#' @param cov The current covariance matrix
#' @param v the new parameter values
#' @param means the current means of the parameters
#' @param n The number of posterior (mcmc) samples taken till now
#' @return The updated covariance matrix given the new parameter sample
#'
.updateCovariance <- function(cov, v, means, n) {
    .Call('fluEvidenceSynthesis_updateCovariance', PACKAGE = 'fluEvidenceSynthesis', cov, v, means, n)
}

#' Convert given week in given year into an exact date corresponding to the Monday of that week
#'
#' @param week The number of the week we need the date of
#' @param year The year
#' @return The date of the Monday in that week 
#'
getTimeFromWeekYear <- function(week, year) {
    .Call('fluEvidenceSynthesis_getTimeFromWeekYear', PACKAGE = 'fluEvidenceSynthesis', week, year)
}

#' Run the SEIR model for the given parameters
#'
#' @param age_sizes A vector with the population size by each age {1,2,..}
#' @param vaccine_calendar A vaccine calendar valid for that year
#' @param polymod_data Contact data for different age groups
#' @param current_state The parameters needed to run the ODE model
#' @return A data frame with number of new cases at each day during the year
#'
.runSEIRModel <- function(age_sizes, vaccine_calendar, polymod_data, current_state) {
    .Call('fluEvidenceSynthesis_runSEIRModel', PACKAGE = 'fluEvidenceSynthesis', age_sizes, vaccine_calendar, polymod_data, current_state)
}

#' Run an ODE model with the runge-kutta solver for testing purposes
#'
.runRKF <- function() {
    .Call('fluEvidenceSynthesis_runPredatorPrey', PACKAGE = 'fluEvidenceSynthesis')
}

#' Calculate number of influenza cases given a vaccination strategy
#'
#' @param age_sizes A vector with the population size by each age {1,2,..}
#' @param vaccine_calendar A vaccine calendar valid for that year
#' @param polymod_data Contact data for different age groups
#' @param sample The parameters needed to run the ODE model (typically one of the posterior sample created when running the inference)
#' @return A data frame with the total number of influenza cases in that year
#'
vaccinationScenario <- function(age_sizes, vaccine_calendar, polymod_data, sample) {
    .Call('fluEvidenceSynthesis_vaccinationScenario', PACKAGE = 'fluEvidenceSynthesis', age_sizes, vaccine_calendar, polymod_data, sample)
}

