# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cholesky <- function(A) {
    .Call('fluEvidenceSynthesis_cholesky', PACKAGE = 'fluEvidenceSynthesis', A)
}

rcpp_hello_world <- function() {
    .Call('fluEvidenceSynthesis_rcpp_hello_world', PACKAGE = 'fluEvidenceSynthesis')
}

getIMMDate <- function(mon, year) {
    .Call('fluEvidenceSynthesis_getIMMDate', PACKAGE = 'fluEvidenceSynthesis', mon, year)
}

