# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' MCMC based inference of the parameter values given the different data sets
inference <- function(age_sizes, ili, mon_pop, n_pos, n_samples, vaccine_calendar, polymod_data, init_state, mcmc_chain_length = 100000L, burn_in = 10000L, thinning = 100L) {
    .Call('fluEvidenceSynthesis_inference', PACKAGE = 'fluEvidenceSynthesis', age_sizes, ili, mon_pop, n_pos, n_samples, vaccine_calendar, polymod_data, init_state, mcmc_chain_length, burn_in, thinning)
}

#' Update means when a new posterior sample is calculated
updateMeans <- function(means, v, n) {
    .Call('fluEvidenceSynthesis_updateMeans', PACKAGE = 'fluEvidenceSynthesis', means, v, n)
}

#' Update covariance matrix of posterior parameters
#'
#' Used to enable faster mixing of the mcmc chain
updateCovariance <- function(cov, v, means, n) {
    .Call('fluEvidenceSynthesis_updateCovariance', PACKAGE = 'fluEvidenceSynthesis', cov, v, means, n)
}

#' Convert given week in given year into an exact date corresponding to the Monday of that week
getTimeFromWeekYear <- function(week, year) {
    .Call('fluEvidenceSynthesis_getTimeFromWeekYear', PACKAGE = 'fluEvidenceSynthesis', week, year)
}

#' Run the SEIR model for the given parameters
runSEIRModel <- function(age_sizes, vaccine_calendar, polymod_data, current_state) {
    .Call('fluEvidenceSynthesis_runSEIRModel', PACKAGE = 'fluEvidenceSynthesis', age_sizes, vaccine_calendar, polymod_data, current_state)
}

#' Calculate number of influenza cases given a vaccination strategy
vaccinationScenario <- function(age_sizes, vaccine_calendar, sample, polymod_uk) {
    .Call('fluEvidenceSynthesis_vaccinationScenario', PACKAGE = 'fluEvidenceSynthesis', age_sizes, vaccine_calendar, sample, polymod_uk)
}

